# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_4_0_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='printable',
            field=models.BooleanField(default=False),
        ),
    ]
